apiVersion: v1
kind: Service
metadata:
  name: rancher-monitoring-prometheus
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: rancher-monitoring-prometheus
