apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: my-app
          image: w3ll1n9t0n/metrics:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app.py
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
