apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-page-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-page
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
