apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-page:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80  
    targetPort: 80
  type: LoadBalancer  # Add this line to enable a load balancer
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webcolor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webcolor
  minReplicas: 2  # Set the minimum number of replicas
  maxReplicas: 5  # Set the maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Set the target CPU utilization percentage
